"""Export utilities for ChunkCanvas"""

import os
import tempfile
from datetime import datetime

import pandas as pd

from chunkcanvas.config.constants import DOCUMENT_WITH_TABLES, EXCEL_SPREADSHEET, SIMPLE_TEXT


def generate_export_script(form_data, api_keys, document_type, pinecone_environment, index_name):
    """Generate a Python script with all the parameters from the current session"""
    
    # Get the separator list as a string
    if "separators" in form_data:
        separators_str = ", ".join([f"'{sep}'" for sep in form_data.get("separators", [])])
    else:
        separators_str = "'---', '/n', '.'"
    
    # Initialize script with imports
    script = f'''# Generated by ChunkCanvas on {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}
import os
import tempfile
from langchain_core.documents import Document
from langchain_pinecone import PineconeVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_voyageai import VoyageAIEmbeddings
from pinecone import Pinecone
'''

    # Add document type specific imports
    if document_type == DOCUMENT_WITH_TABLES:
        script += 'from llama_parse import LlamaParse\n'
    elif document_type == EXCEL_SPREADSHEET:
        script += 'import pandas as pd\n'
    else:
        script += 'import docx2txt\nimport PyPDF2\n'
    
    script += '\n# API Keys\n'
    
    # Add API keys as environment variables
    for key_name, key_value in api_keys.items():
        if key_name == "pinecone_env":
            continue
        if key_value:  # Only add non-empty keys
            script += f"os.environ['{key_name.upper()}_API_KEY'] = '{key_value}'\n"
    
    # Add configuration parameters
    script += '\n# Configuration parameters\n'
    script += f"PINECONE_ENVIRONMENT = '{pinecone_environment}'\n"
    script += f"INDEX_NAME = '{index_name}'\n"
    script += f"DOCUMENT_TYPE = '{document_type}'\n\n"
    
    # Add chunking parameters
    script += '# Chunking parameters\n'
    script += f"chunk_size = {form_data.get('chunk_size', 4096)}\n"
    script += f"chunk_overlap = {form_data.get('chunk_overlap', 50)}\n"
    script += f"separators = [{separators_str}]\n\n"
    
    # Document specific parameters
    if document_type == DOCUMENT_WITH_TABLES:
        script += '# LlamaParse parameters\n'
        script += 'llamaparse_params = {\n'
        for key, value in form_data.items():
            if key not in ['chunk_size', 'chunk_overlap', 'separators']:
                if isinstance(value, str):
                    script += f"    '{key}': '{value}',\n"
                else:
                    script += f"    '{key}': {value},\n"
        script += '}\n\n'
    elif document_type == EXCEL_SPREADSHEET:
        script += f"column_name = '{form_data.get('column_name', 'Column1')}'\n\n"
    
    # Add document processing function
    script += '# Document processing function\n'
    if document_type == DOCUMENT_WITH_TABLES:
        script += '''def process_document(file_path):
    """Process document with LlamaParse"""
    # Add API key to params
    params = llamaparse_params.copy()
    params["api_key"] = os.environ.get("LLAMA_CLOUD_API_KEY", "")
    
    # Initialize parser with parameters
    parser = LlamaParse(verbose=True, **params)
    
    # Parse document
    parsed_document = parser.load_data(file_path)
    return parsed_document[0].text
'''
    elif document_type == EXCEL_SPREADSHEET:
        script += '''def process_document(file_path):
    """Process Excel spreadsheet"""
    df = pd.read_excel(file_path)
    return df[column_name].tolist()
'''
    else:
        script += '''def process_document(file_path):
    """Process simple text document"""
    file_extension = file_path.split(".")[-1].lower()
    
    if file_extension == "pdf":
        with open(file_path, "rb") as f:
            pdf_reader = PyPDF2.PdfReader(f)
            return "\\n".join(page.extract_text() for page in pdf_reader.pages)
    elif file_extension == "docx":
        return docx2txt.process(file_path)
    elif file_extension in ["txt", "md"]:
        with open(file_path, "r", encoding="utf-8") as f:
            return f.read()
    else:
        raise ValueError(f"Unsupported file type: {file_extension}")
'''
    
    # Add chunking function
    script += '\n# Chunking function\n'
    script += '''def create_chunks(content, file_name):
    """Create document chunks from content"""
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        length_function=len,
        separators=separators
    )
    
    # For Excel files, content is a list of rows
    if DOCUMENT_TYPE == 'Excel Spreadsheet':
        doc_chunks = []
        for row in content:
            chunks = text_splitter.create_documents([str(row)], metadatas=[{"filename": file_name}])
            doc_chunks.extend(chunks)
        return doc_chunks
    else:
        # For text and document with tables
        return text_splitter.create_documents([content], metadatas=[{"filename": file_name}])
'''
    
    # Add upload function
    script += '\n# Upload function\n'
    script += '''def upload_to_pinecone(doc_chunks):
    """Upload document chunks to Pinecone"""
    pc = Pinecone(api_key=os.environ.get("PINECONE_API_KEY", ""), environment=PINECONE_ENVIRONMENT)
    
    # Initialize embeddings
    embeddings = VoyageAIEmbeddings(model="voyage-3", api_key=os.environ.get("VOYAGE_API_KEY", ""))
    
    # Initialize vectorstore
    vectorstore = PineconeVectorStore(
        index_name=INDEX_NAME,
        embedding=embeddings,
    )
    
    # Upload documents
    print(f"Uploading {len(doc_chunks)} chunks to Pinecone index: {INDEX_NAME}")
    vectorstore.add_documents(doc_chunks)
    print("Upload complete!")
'''
    
    # Add main execution
    script += '\n# Main execution\n'
    script += '''def main(file_path):
    """Process a document and upload it to Pinecone"""
    print(f"Processing document: {file_path}")
    
    # Process document
    content = process_document(file_path)
    
    # Create chunks
    file_name = file_path.split("/")[-1]
    doc_chunks = create_chunks(content, file_name)
    print(f"Created {len(doc_chunks)} chunks")
    
    # Upload chunks
    upload_to_pinecone(doc_chunks)

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Process and upload a document to Pinecone")
    parser.add_argument("file_path", help="Path to the document file")
    args = parser.parse_args()
    
    main(args.file_path)
'''
    
    return script


def export_script_to_file(script_content):
    """Save script content to a file and provide it for download"""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    script_filename = f"chunk_canvas_export_{timestamp}.py"
    
    # Create a temporary file
    with tempfile.NamedTemporaryFile(delete=False, suffix='.py', mode='w') as temp_file:
        temp_file.write(script_content)
        temp_file_path = temp_file.name
    
    # Read the file for download
    with open(temp_file_path, 'r') as f:
        script_bytes = f.read().encode()
    
    # Clean up the temporary file
    os.unlink(temp_file_path)
    
    return script_bytes, script_filename


def generate_requirements_txt(document_type):
    """Generate a requirements.txt file content based on the document type"""
    # Base requirements for all document types
    requirements = [
        "langchain-core>=0.1.16",
        "langchain-pinecone>=0.1.4",
        "langchain-text-splitters>=0.1.0",
        "langchain-voyageai>=0.0.3",
        "pinecone-client>=3.0.0",
        "pandas>=2.0.0",
    ]
    
    # Add document type specific requirements
    if document_type == DOCUMENT_WITH_TABLES:
        requirements.extend([
            "llama-parse>=0.3.3",
        ])
    elif document_type == EXCEL_SPREADSHEET:
        requirements.extend([
            "openpyxl>=3.1.2",
        ])
    else:  # SIMPLE_TEXT
        requirements.extend([
            "docx2txt>=0.8",
            "PyPDF2>=3.0.0",
        ])
    
    # Sort requirements alphabetically
    requirements.sort()
    
    return "\n".join(requirements)